spring.application.name=devis

spring.datasource.url=jdbc:h2:mem:laboccaz_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.profiles.active=local

bubble.api.base-url=https://app.laboccaz.com/version-63d6t/api/1.1/obj
#bubble.api.token=bca4187668e1a671da73146239f00a19
bubble.api.token=${BUBBLE_API_TOKEN:}


